--- UPDATE STATS for infa_dis_db
/*
select 'UPDATE STATISTICS '+name+'
WITH FULLSCAN'+CHAR(13)+ 'GO '+CHAR(13)
, *
from sys.tables

where type_desc = N'USER_TABLE'
*/
UPDATE STATISTICS AeAlarm
WITH FULLSCAN
GO 
UPDATE STATISTICS AeAttachment
WITH FULLSCAN
GO 
UPDATE STATISTICS AeB4PDelegate
WITH FULLSCAN
GO 
UPDATE STATISTICS AeB4PTask
WITH FULLSCAN
GO 
UPDATE STATISTICS AeB4PTaskACL
WITH FULLSCAN
GO 
UPDATE STATISTICS AeB4PTaskAttachments
WITH FULLSCAN
GO 
UPDATE STATISTICS AeB4PTaskEventDetail
WITH FULLSCAN
GO 
UPDATE STATISTICS AeB4PTaskPa
WITH FULLSCAN
GO 
UPDATE STATISTICS AeB4PTaskParameter
WITH FULLSCAN
GO 
UPDATE STATISTICS AeB4PTaskParameterValue
WITH FULLSCAN
GO 
UPDATE STATISTICS AeCatalog
WITH FULLSCAN
GO 
UPDATE STATISTICS AeCatalogContribution
WITH FULLSCAN
GO 
UPDATE STATISTICS AeConfigSettings
WITH FULLSCAN
GO 
UPDATE STATISTICS AeContribution
WITH FULLSCAN
GO 
UPDATE STATISTICS AeContributionExport
WITH FULLSCAN
GO 
UPDATE STATISTICS AeContributionImport
WITH FULLSCAN
GO 
UPDATE STATISTICS AeCoordination
WITH FULLSCAN
GO 
UPDATE STATISTICS AeCounter
WITH FULLSCAN
GO 
UPDATE STATISTICS AeDeploymentLog
WITH FULLSCAN
GO 
UPDATE STATISTICS AeEngine
WITH FULLSCAN
GO 
UPDATE STATISTICS AeEventFilter
WITH FULLSCAN
GO 
UPDATE STATISTICS AeFilterProcessState
WITH FULLSCAN
GO 
UPDATE STATISTICS AeFilterPropertiesXref
WITH FULLSCAN
GO 
UPDATE STATISTICS AeGlobalPdefs
WITH FULLSCAN
GO 
UPDATE STATISTICS AeIndexedProperty
WITH FULLSCAN
GO 
UPDATE STATISTICS AeIndexedPropertyForPlan
WITH FULLSCAN
GO 
UPDATE STATISTICS AeIndexedPropertyValue
WITH FULLSCAN
GO 
UPDATE STATISTICS AeLicense
WITH FULLSCAN
GO 
UPDATE STATISTICS AeLock
WITH FULLSCAN
GO 
UPDATE STATISTICS AeMetaInfo
WITH FULLSCAN
GO 
UPDATE STATISTICS AeMomMessage
WITH FULLSCAN
GO 
UPDATE STATISTICS AeOAuthAccessToken
WITH FULLSCAN
GO 
UPDATE STATISTICS AePartnerLinks
WITH FULLSCAN
GO 
UPDATE STATISTICS AePlan
WITH FULLSCAN
GO 
UPDATE STATISTICS AePlanImage
WITH FULLSCAN
GO 
UPDATE STATISTICS AePlanResource
WITH FULLSCAN
GO 
UPDATE STATISTICS AePojo
WITH FULLSCAN
GO 
UPDATE STATISTICS AeProcess
WITH FULLSCAN
GO 
UPDATE STATISTICS AeProcessAttachment
WITH FULLSCAN
GO 
UPDATE STATISTICS AeProcessDefInfo
WITH FULLSCAN
GO 
UPDATE STATISTICS AeProcessJournal
WITH FULLSCAN
GO 
UPDATE STATISTICS AeProcessLogData
WITH FULLSCAN
GO 
UPDATE STATISTICS AeQueuedReceive
WITH FULLSCAN
GO 
UPDATE STATISTICS AeScheduler
WITH FULLSCAN
GO 
UPDATE STATISTICS AeService
WITH FULLSCAN
GO 
UPDATE STATISTICS AeServiceAllowedRoles
WITH FULLSCAN
GO 
UPDATE STATISTICS AeSite
WITH FULLSCAN
GO 
UPDATE STATISTICS AeSiteLock
WITH FULLSCAN
GO 
UPDATE STATISTICS AeSiteSync
WITH FULLSCAN
GO 
UPDATE STATISTICS AeSubscription
WITH FULLSCAN
GO 
UPDATE STATISTICS AeSystemLog
WITH FULLSCAN
GO 
UPDATE STATISTICS AeTenant
WITH FULLSCAN
GO 
UPDATE STATISTICS AeTransmissionTracker
WITH FULLSCAN
GO 
UPDATE STATISTICS AeURNValues
WITH FULLSCAN
GO 
UPDATE STATISTICS AeVariable
WITH FULLSCAN
GO 
UPDATE STATISTICS AeWsrmStateTracker
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_AGG_RES_SMRY
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_AGG_RES_SMRY_DTL
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_CDC_EXTRACTION
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_CKE_EXCLUDE_CUR_RULE
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_CKE_EXCLUDE_CURATION
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_CKE_RES_SMRY
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_DATA_DOM_INF_RES_SMRY
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_DATA_DOMAIN_GRPS
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_DATA_DOMAINS
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_DATADOMAIN_DEF
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_DATATYPE_INF_RES_SMRY
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_DD_EXCLUDE_CUR_RULE
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_DD_EXCLUDE_CURATION
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_DOM_INF_RES_SMRY
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_DT_EXCLUDE_CUR_RULE
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_DT_EXCLUDE_CURATION
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_DVC_RES_SMRY
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_EXCLUDED_DT_FUNCTION_RES
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_EXCLUDED_FUNCTION_RES
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_FDA_RES_SMRY
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_FIELD_BRV_RES_SMRY
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_FIELD_DEFN
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_FIELD_RUN
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_FIELD_VERBOSE_SMRY_DATA
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_FIELD_VIEW
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_FILE_LOCATION
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_FREQ_OUTLIERS
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_FUNCTION_GROUPBY_FIELDS
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_FUNCTION_JOIN_CONDITIONS
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_FUNCTION_RES
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_FUNCTION_RES_FIELDS
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_FUNCTION_RES_SMRY
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_FUNCTION_VIEW
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_GROUPBY_FIELD_RES_DTL
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_HISTORIC_THRESHOLDS
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_INCRPROF_RUN_INFO
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_INVALID_DATA_COST
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_ISSA_FIELDS
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_ISSA_RES_SMRY
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_JCE_RES_SMRY
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_JCE_RES_SMRY_DTL
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_JOIN_CONDITION_FIELDS
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_JOIN_VERBOSE_SMRY_DATA
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_MULTIRECORD_DEFN
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_OUTLIER_FIELD_SMRY
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_OUTLIER_PT_SMRY
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_PATTERN_OUTLIERS
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_PK_FK_RES_SMRY
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_PKFK_EXCLUDE_CUR_RULE
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_PKFK_EXCLUDE_CURATION
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_PQ_PT_CONTEXT
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_PQ_PT_RUN_INFO
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_PQ_SERIALIZED_PR
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_PQ_SERIALIZED_PT
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_PROFILE_COMMIT_CKE
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_PROFILE_COMMIT_DATADOMAIN
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_PROFILE_COMMIT_DT
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_PROFILE_COMMIT_PKFK
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_PROFILE_DEFINITION
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_PROFILE_RUN
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_PROFILE_VERSION
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_PROFILETASK_DEFINITION
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_PROFSRC_COLUMN_DEF
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_REC_SELECTED_FIELDS
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_RECORD_BRV_RES_SMRY
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_RECORD_DEFN
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_RECORD_RUN
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_RECORD_VIEW
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_REDUN_RES_SMRY
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_RESOURCE_VIEW
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_RESULT_PURGE_REQUEST
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_RESULT_RUN_PURGEREQ
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_RIA_RES_SMRY
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_ROW_CNT_RES_SMRY
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_ROW_UNIQ_RES_SMRY
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_RULE_VIEW
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_SAMPLING_METRICS
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_SCORE_SMRY_RES
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_SEQ_KEYS
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_SIGNATURE
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_SOURCE_DEFINITION
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_SOURCE_GROUP
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_SOURCE_GROUP_DETAILS_DD
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_SOURCE_GROUP_DETAILS_PKFK
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_SOURCE_GROUP_SMRY
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_SOURCE_INFO
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_SRC_COMMIT_CKE
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_SRC_COMMIT_DATADOMAIN
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_SRC_COMMIT_DT
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_SRC_COMMIT_PKFK
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_STAT_DSO
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_VAL_FREQ_OUTLIERS
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_VALID_VALUES
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_VERBOSE_FIELD_DTL_RES
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_VERBOSE_SMRY_DATA
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_VERBOSE_SOURCE_MAP
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_WEIGHTED_AVG
WITH FULLSCAN
GO 
UPDATE STATISTICS IDP_WH_VERSION
WITH FULLSCAN
GO 
