USE informatica_models
GO

--- UPDATE STATS for infa_dis_db
 /*
select 'UPDATE STATISTICS '+name+'
WITH FULLSCAN'+CHAR(13)+ 'GO '+CHAR(13)
, *
from sys.tables

where type_desc = N'USER_TABLE'
*/ 

UPDATE STATISTICS PC_AUDITLOG
WITH FULLSCAN
GO 
UPDATE STATISTICS PC_DBOBJECT
WITH FULLSCAN
GO 
UPDATE STATISTICS PC_DBRCONFIG
WITH FULLSCAN
GO 
UPDATE STATISTICS PC_ICLASS_SIG
WITH FULLSCAN
GO 
UPDATE STATISTICS PC_NAMESPACE
WITH FULLSCAN
GO 
UPDATE STATISTICS PC_NAMESPACE_SEQUENCE
WITH FULLSCAN
GO 
UPDATE STATISTICS PC_ORMSTATE
WITH FULLSCAN
GO 
UPDATE STATISTICS PC_PACKAGE
WITH FULLSCAN
GO 
UPDATE STATISTICS PC_PREPROCESS_KV_ENTRY
WITH FULLSCAN
GO 
UPDATE STATISTICS PC_REPOSITORY
WITH FULLSCAN
GO 
UPDATE STATISTICS PC_UPGRADE_LOG
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ABSTRACTCATCHABLEEVEN1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ABSTRACTCATCHABLEEVENT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ABSTRACTHUMANFLOWCONFI
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ABSTRACTLOADBALANCINGC
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ABSTRACTPARAMETERBINDI
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ABSTRACTPARAMETERCONTE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ABSTRACTPAYLOAD
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ABSTRACTPROPERTYVALUE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ABSTRACTSAPPACKAGE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ABSTRACTSCHEMA
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ABSTRACTSCHEMAITEM
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ABSTRACTSEQUENCEOBJECT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ABSTRACTTARGE1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ABSTRACTTARGET
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ABSTRACTTAS1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ABSTRACTTAS2
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ABSTRACTTASK
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ABSTRACTTASKEXECUTIONC
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ABSTRACTTHROWABLEEVEN1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ABSTRACTTHROWABLEEVENT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ABSTRACTTRANSFORMATION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ABSTRACTVALU1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ABSTRACTVALUE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ABSTRACTVIEW
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ACE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ACEANNOTATION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ACTIVITINSTANCEHISTORY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ADVANCEDPARAMETER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ADVANCEDSIGNATURE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_AGGREGATETIMESTAMP
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_AGGREGATIONTYPE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_AGGREGATIONTYPECONTAIN
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ALERTCONFIG
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ANNOTATION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_APPLICATION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_APPLICATIONDATAOBJECTS
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_APPLICATIONGROUP
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_APPLICATIONREGISTRYENT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_APPLICATIONSPEC
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_APPLICATIONSTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ASSIGNMENTEXPRESSION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ATTACHMENT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ATTACHMENTHISTORY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ATTRIBUT1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ATTRIBUT2
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ATTRIBUTE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ATTRIBUTES
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_AVBASEREPORT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_AVOPTION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BACKPOINTER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BASECADIENGINECONFIG
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BEANSTATS
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGACL
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGASSETPROPERTIES
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGATTRIBUTE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGATTRIBUTEDEFINITION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGATTRIBUTEINSTANCE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGATTRIBUTEVALUE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGAUDITHISTORY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGCATEGORY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGCATEGORYRELATIONSHIP
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGGLOSSARY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGGLOSSARYPRIVILEGEMAP
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGINITIATIVE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGINITIATIVEOBJECT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGLINEAGEFILTER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGPOLICY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGPOLICYRELATIONSHIP
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGPRIVILEGE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGPRIVILEGEASSIGNMENT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGPROPERTY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGPROPERTYGROUP
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGPROPERTYVALUE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGRELATIONSHIPTYPE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGROLE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGRULE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGSYNONYM
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGTEMPLATE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGTEMPLATEELEMENT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGTEMPLATEELEMENTCONTR
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGTEMPLATELAYOUT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGTERM
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGTERMRELATIONSHIP
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGUSER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGUSEROBJECTASSOCIATIO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BGVOTINGTASKRESULT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BOXEDRECEIVEROBJEC1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BOXEDRECEIVEROBJECT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BUFFERBLOCK
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_BYTEARRAY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CADISESSIONSTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CADISESSIONSTATSUMMARY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CALLBACKMESSAGE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CANONICALDATAMODEL
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CAPABILIT1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CAPABILITY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CASCADEIUDOPTIONS
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CASTSETTING
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CHANGELIST
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CHANGELISTOBJECT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CHARACTERISTI1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CHARACTERISTI2
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CHARACTERISTI3
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CHARACTERISTIC
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CHARACTERRANGE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CLASSIFIEROPERATION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CLUSTERCONF
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CLUSTERCONFIGURATION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CLUSTERINGPORT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CLUSTERINGSTRATEGY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CODEPAGE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CODEPAGESYSTEM
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_COLLECTIONENTRY_0
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_COLLECTIONENTRY_1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_COLLECTIONENTRY_2
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_COLLECTIONENTRY_3
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_COLLECTIONENTRY_4
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_COLLECTIONENTRY_5
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_COLLECTIONENTRY_6
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_COLLECTIONENTRY_7
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_COLLECTIONENTRY_8
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_COLLECTIONENTRY_9
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_COLUMNFEATURE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_COLUMNSTRATEG1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_COLUMNSTRATEGY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_COMMEN1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_COMMENT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_COMMENTEDOBJECT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_COMMENTHISTORY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_COMMONOUTCOMECONTAINER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_COMPONENT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_COMPONENTINTERFACE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_COMPOSITEDATADOMAIN
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_COMPOSITEDOMAINELEMENT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_COMPOSITEDOMAININFEREN
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CONDITIO1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CONDITION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CONFFETCHERPARAMETER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CONFIGOBJECT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CONFNAMESPACE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CONFPROPERTY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CONNECTINFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CONNECTINFOCLASSIFIERC
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CONNECTIONINFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CONNECTIONPOOLATTRIBUT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CONNECTIONREFERENCE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CONNECTIONSTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CONSOLIDATIONCONFIGURA
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CONTACTDETAILS
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CONTENTCONTAINER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CORRELATIONINFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_COSTCOEFFICIENTCONFIG
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_COSTCOEFFICIENTS
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_COUNTERSTATE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CRITERION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_CUSTOMPROPERTY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_D_ARC
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_D_CAPABILITYATTRIBUTES
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_D_FIELDBASE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_D_MODELEXTENSIONCALLCA
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_D_MODELEXTENSIONLOOKUP
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_D_MODELEXTENSIONOPERAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_D_MODELEXTENSIONREADCA
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_D_MODELEXTENSIONWRITEC
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_D_OPERATIONBASE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_D_PROJECTION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_D_REUSABLEEXPRESSION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DARC
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DATAACCESSGROUP
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DATAADAPTER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DATADOMAIN
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DATADOMAINCREATIONCRIT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DATADOMAINGROUP
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DATADOMAINMEMBERSHIPDE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DATAELEMENTREF
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DATAHANDLER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DATAINTERFACE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DATAMAPTYPE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DATAOBJECT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DATAOBJECTACCESSSTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DATAOBJECTATTRIBUTE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DATAOBJECTCACHEINSTAN1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DATAOBJECTCACHEINSTANC
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DATAOBJECTINFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DATAOBJECTKEY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DATAOBJECTREFERENCE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DATAOBJECTSTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DATAOBJECTTYPEINFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DATAPARTITIONINGSTRATE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DATASERVICECONFIG
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DATASOURCE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DATASOURCEOPERATION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DATATYPECONVERSION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DATATYPEMAP
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DEFAULTOSPROFILE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DEFINITION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DEPLOYEDNS
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DEPLOYMENT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DEPLOYMENTDIAGNOSTIC
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DEPLOYMENTRECORD
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DEPLOYMENTREQUEST
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DERIVEDFIELDSET
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DETAILEDDOMAINEVENTSTA
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DETAILHISTORY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DFIELD
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DGRAPH
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DGROUPNODE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DICTIONARY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DIGESTPOLICY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DNODE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DOCUMENT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DOMAINEVENTSTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DOMAININFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DOMAINPROXIMITYDEFINIT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DOMAINSERVICEPROCESSEV
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DPRUNPARAMETERS
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DQCONTENTITEM
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DQOBJECT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DSCIBASE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DSNAMEDELEMENT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DSORUNTIMECONFIG
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DTBUNDLE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DTDOCUMENT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DTOBJECT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DTP
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DTPEXPORTMANIFEST
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DTPORTBINDING
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DTPPROXY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DTSERVICE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DTSTRUCTURALFEATUREOVE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DYNAMICCACHEFIELD
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_DYNAMICLOADBALANCINGTA
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ELEMENT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_EMAILATTACHMENT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_EMAILCONFIG
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_EMAILCONTENT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ENCODING
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ENDPOINT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ENTITYFIELDDESCRIPTOR
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ENUMERATEDVALUEQUALIFI
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_EXECUTION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_EXECUTIONENVIRONMENT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_EXECUTIONENVIRONMENTTY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_EXECUTIONINFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_EXECUTIONITEM
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_EXECUTIONPARAMETER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_EXECUTIONPLAN
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_EXECUTIONSTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_EXECUTIONSTEP
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_EXECUTIONSTEPDEPENDENC
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_EXECUTIONSTEPSTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_EXPRESSIO1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_EXPRESSION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_EXTENSIBILITYELEMENT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_EXTENSIBLEELEMENTEXTER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_EXTENSIBLEELEMENTINTER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_EXTENSIONATTRIBUTE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_EXTENSIONCONTAINER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_EXTENTION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_FAILURE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_FEATURE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_FEATUREPATH
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_FEATUREREGISTRYENTRY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_FIELDDESCRIPTOR
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_FIELDMAPLINKAGE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_FIELDMAPSPEC
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_FIELDPARAMETER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_FIELDSELECTORSCOP1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_FIELDSELECTORSCOPE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_FIELDTESTDATA
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_FILEINF1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_FILEINFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_FILTER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_FILTERCONDITION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_FILTERCRITERIA
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_FIXEDSHIFTSTATE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_FLATBYTEDEFINITION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_FLATBYTEEXTENSION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_FOLDER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_FOREIGNKE1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_FOREIGNKEY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_FOREIGNKEYS
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_FREQUENCYCELL
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_FTPCONNECTIONATTRIBUTE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_FUNCTION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_FUNCTIONALDEPENDENCY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_FUNCTIONCATEGORY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_FUNCTIONCONTAINER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_FUNCTIONDEFINITIO1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_FUNCTIONDEFINITION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_FUNCTIONGROU1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_FUNCTIONGROUP
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_GENERATESTRATEGY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_GENERATIONSTRATEGY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_GENERICDATAHANDLINGOPT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_GLOBALNOTIFICATIONCONF
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_GLOSSARY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_GROUPDOCUMENTOBJECT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_GROUPENGINE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_GROUPPARTITIONINGSCHEM
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_GROUPSTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_HADOOPCLUSTERINFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_HADOOPDISTRIBUTION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_HADOOPEXECUTIONCONFIG
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_HADOOPEXECUTIONPARAMET
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_HADOOPIMPERSONATIONPRO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_HCOMPONENT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_HEADER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_HGROUP
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_HIERARCHICALPATTERN
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_HISTORYSUMMARY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_HIVEINFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_HIVEPUSHDOWNENGINECONF
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_HIVESESSIONSTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_HIVESESSIONSTATSUMMARY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_HPORT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_HTTPFILEINFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_IDENTITYLINK
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_IDMSSETOWNER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_IDOBJ
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_IDTOQUALNAMES
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ILMCONNECTION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ILMCONNECTIONPROPERTY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_IMFPACKAGEUPGRADEINFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_INJECTIONPOINT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_INPUT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_INPUTBINDIN1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_INPUTBINDING
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_INSTANC1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_INSTANCE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_INSTANCELINEAGE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_INVALIDDATACOST
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_INVALIDFIELD
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ISPBOOLEAN
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ISPINTEGER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ISPLONG
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ISPSTRING
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_JOB
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_JOIN
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_JOINCONDITIO1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_JOINCONDITION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_KE1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_KEY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_KEYFIELD
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_KEYRANGEFIELD
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_KEYSTATISTICS
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_KEYTABAUTHPARAMS
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_KEYVALU1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_KEYVALU2
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_KEYVALUE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_KEYVALUECOLLECTION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_L_ARC
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_L_CONDITION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_L_CONSTRAINT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_L_DATAFORMATCONFIG
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_L_GRAPH
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_L_INDEX
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_L_INDEXFIELD
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_L_MODELEXTENSIONARC
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_L_MODELEXTENSIONCONDIT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_L_MODELEXTENSIONCONSTR
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_L_MODELEXTENSIONDATAFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_L_MODELEXTENSIONFIELDB
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_L_MODELEXTENSIONGRAPH
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_L_MODELEXTENSIONINDEX
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_L_MODELEXTENSIONINDEXF
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_L_MODELEXTENSIONNODE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_L_NODE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_LABEL
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_LARC
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_LBINARYCONTAINER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_LBLOB
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_LCONTAINER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_LDAPNAMESPACE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_LDAPOPTIONS
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_LGRAPH
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_LIBRAR1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_LIBRAR2
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_LIBRAR3
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_LIBRARY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_LIGHTATTRIBUTE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_LIGHTFLOW
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_LIGHTTASKINSTANCE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_LIGHTWORKFLOW
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_LINK
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_LINKAGEORDER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_LINKATTRIBUTES
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_LINKPOLICY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_LNODE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_LOADBALANCINGINFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_LOADORDERCONSTRAINT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_LOADORDERSTRATEGY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_LOCKEDOBJECT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_LOCKEDOBJECTSUMMARY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_LOGICALDB
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_LOGICALRESOURCE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_LOGICALSCHEMA
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_LOGMESSAGE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_LOOKU1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_LOOKUP
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_LSCIBASE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MACCESSCONTROLENTRY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MACCESSCONTROLENTRYANN
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MACCESSCONTROLLIST
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MAPPING
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MAPPINGFEATURECONFIG
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MAPPINGFEATURESTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MAPPINGLINEAGE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MAPPINGOUTPUTCONTAINER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MAPPINGPERSISTEDOUTPU1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MAPPINGPERSISTEDOUTPUT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MAPPINGPROXY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MAPPINGRUNINFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MAPPINGRUNREQUESTSTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MAPPINGSPEC
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MAPPINGSTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MAPPLETINTERFACECARDIN
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MASKINGDATA
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MASTERLOOKUPFIELDROLE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MEDOMAIN
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MEDOMAINDEFINITION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MERGEKIND
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MESSAG1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MESSAGE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MESSAGEBODY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MESSAGEITEM
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MESSAGES
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_METADATACONNECTIONSPEC
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_METADATAEXTENSIONATTRI
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_METADATAREPOSITORY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MODELENUMENTRY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MODELREPOSITORY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MONITORINGAGGREGATESTA
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MPPROCESSEDDATAUPGRADE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MPPROJECT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MPPROJECTGROUP
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MPSEARCHSYSTEMINFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_MPSERVICEINFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_NAMERULEENTRIES
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_NAMESPACE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_NAMESPACECONTENT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_NAMESPACEREF
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_NAMESPACETOPREFIXMAP
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_NAMEVALUEPAI1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_NAMEVALUEPAIR
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_NATIVEPARTITIONINGCONF
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_NATIVESESSIONSTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_NATIVESESSIONSTATSUMMA
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_NESTEDITEM
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_NESTEDSCOPEDESCRIPTOR
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_NLPENTITY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_NODEADDRESS
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_NODEHOURLYSUMMARIZEDST
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_NODELEVELSUMMARIZATION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_NODEPROCESSSTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_NODEPROCESSTUPLEIDENTI
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_NODEREF
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_NORMALIZERNODE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_NORMALIZERSRCFIELD
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_NOTIFICATIO1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_NOTIFICATION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_NOTIFICATIONCONFIG
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_NOTIFICATIONCONFIGPROP
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_NOTIFICATIONS
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_NOTIFICATIONSELECTOR
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_NOTIFICATIONTRANSPORTI
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_NUMBERSETVALUERULE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_OBJECTGRAPHDECORATION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_OBJECTHISTORY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_OBJECTIDENTIFIER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_OBJECTREFCONTAINER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_OBJECTREFERENC1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_OBJECTREFERENCE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_OBJECTSCOPEDESCRIPTOR
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_OPTIMIZERCONFIG
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_OPTIO1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_OPTION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_OPTIONGROUP
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_OPTIONSET
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_OSPROFILE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_OSPROFILEPRODUCTEXTENS
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_OUTCOME
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_OUTLINELINK
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_OUTPUT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_OUTPUTBINDIN1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_OUTPUTBINDING
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_OUTPUTEXPRESSION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_OUTPUTFIELD
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_OUTPUTFIELDLINK
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_OUTPUTMAP
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_OUTPUTSTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_OUTPUTVALUE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PAIRGENCONFIGURATION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PARAM
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PARAMETE1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PARAMETE2
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PARAMETER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PARAMETERCONTAINER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PARAMETERENTRY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PARAMETERMODEL
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PARAMETERREFERENCE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PARAMETERSET
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PARAMETERTYPE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PARAMETERVALUE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PARAMETERVALUEMODEL
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PARAMETERVALUESMODEL
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PARAMFIELDMAPPORT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PARAMFIELDMAPPORTWRAPP
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PARAMLOCATOR
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PARAMVAL
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PARC
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PARENTINFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PARSEROPERATION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PARSESTRATEGY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PARTITIONALLOCATIONSTR
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PARTITIONINGKEY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PARTITIONINGKEYRANGES
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PARTITIONINGKEYVALUES
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PARTITIONINGSCHEME
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PARTITIONKEYRANGE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PARTITIONPOINT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PATTERNPARSEROPERATION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PCAPABILITYINFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PERMISSION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PERMISSIONLIST
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PFIELD
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PGRAPH
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PIMFPACKAGEINFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PLANINFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PNODE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PORT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PORTLINEAGE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PORTPOLICY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PREFERENCE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PREGISTEREDCAPABILITIE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PRIMARYKEY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PRIMITIVEVALUE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PRINCIPAL
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PRIVILEGE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PROCESSDEFINITION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PROCESSINSTANCEHISTORY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PROCESSSTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PROCESSSTATSUMMARY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PROFILEABLEDATADOMAIN
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PROFILEABLEFIEL1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PROFILEABLEFIELD
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PROFILEABLERECOR1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PROFILEABLERECORD
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PROFILEDEFINITIO1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PROFILEDEFINITION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PROFILETASK
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PROFILETUNIN1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PROFILETUNING
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PROJECT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PROJECTGROUPTENANTMAPP
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PROJECTSCOPEDESCRIPTOR
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PROPERT1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PROPERT2
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PROPERTY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PROPERTYVALUE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PROPIDTOCOLUMN
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PSCIBASE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PWXASOOPERATIONFIELD
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PWXCONNECTIVITYTYPE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PWXDATAMAPPROPERTIES
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PWXFIELDINFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_PWXRECORDLEVELEXIT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_QUERYFILTERPARAMS
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_QUERYRESULT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RANGESTATISTICS
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RANGEVALUE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RARC
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RECIPIENT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RECORD
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RECORDKEY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RECORDSTRATEGY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RECURRENCE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_REFERENCETABLE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RELATIONALCONNECTIVITY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RELATIONALFIELD
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RELATIONALRECORD
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RELATIONALRECORDINSTAN
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RELATIONSHIP
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RENAMEOPTION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_REPOSITORYOPERATIONALI
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_REPOSITORYOPERATIONRES
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_REPOSITORYUPGRADEINFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_REQUESTRESPONSE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_REQUESTSTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RESOURCE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RESOURCEDESCRIPTOR
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RESPONSE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RESPONSESTATUSOBJECT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RESTENDPOINT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RESTFEATURESTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RESTFIELDMETADATA
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RESTFOREIGNIDENTIFIER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RESTIDENTIFIER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RESTOPERATIONSTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RESTPUSHINTOMAPENTRY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RESTRESOURCE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RESULT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RETRYPOLICY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RFIELD
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RHCOMPONENT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RHGROUP
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RNODE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_ROUTINGCONFIG
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RUL1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RULE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RULEDEFINITION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RULEFIELDBINDING
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RULEOUTPUT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RULESPECFIELDBINDING
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RULESPECOUTPUT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RUNNABLEFEATUREINFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RUNPARAMETERS
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RUNTIMEAPPLICATIONSTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RUNTIMEFEATURESTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_RVIEW
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SAMLCONFIG
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SAMPLINGPOLIC1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SAMPLINGPOLICY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SAPABSTRACTSTRUCTURE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SAPASOOPERATIONFIELD
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SAPFILTER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SAPFOREIGNKEY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SAPINDEX
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SAPINDEXFIELD
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SAPPROGRAMINFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SAPRECORDINSTANCE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SAPTABLECONNECTIVITYTY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SAPTABLERESOURCE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SAPUNIQUEKEY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SARCEXTENDEDINFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SCHEDULE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SCHEDULEDDISJOB
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SCHEDULEDTASKRUNSTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SCHEMAALIAS
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SCHEMAPROXY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SCORE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SCORECARD
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SCOREGROUP
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SDKCONNECTBASEATTRIBUT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SDKCONNECTINFOATTR
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SDKCONNECTINFOMODELEXT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SDKCONNECTIONATTRDEF
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SDKCONNECTIONTYPE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SDKDBTYPE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SDKFIELDATTR
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SDKFIELDATTRDEF
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SDKREADERATTR
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SDKREADERATTRDEF
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SDKREADEREXTENSIONTYPE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SDKRECORD
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SECURITYDOMAIN
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SEEDEDNAMESPACECONTENT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SEEDEDOUTPUTSTATSCONTA
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SEMANTICLAYEROPTIONS
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SEQUENCEFLO1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SEQUENCEFLOW
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SEQUENCESTATE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SEQUENCESTATEINFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SERVICEDESCRIPTOR
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SERVICEPRIVILEGEDEF
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SERVICEPROCESSHOURLYSU
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SERVICEPROCESSSTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SERVICEPROCESSTUPLEIDE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SESSION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SETDATEVALUE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SETNUMBERVALUE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SETPARENTCHILDVALUE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SETSTRINGVALUE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SETVALUE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SFIELDEXTENDEDINFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SGRAPHEXTENDEDINFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SIGNATURE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SINGLEEMAILNOTIFICATIO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SNODEEXTENDEDINFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SORT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SORTFIELD
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SORTFIELDLIST
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SORTKE1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SORTKEY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SORTKEYFIELDREF
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SORTKEYFIELDREFLIST
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SORTPORT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SORTSYSTEM
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SOURCE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SOURCECONSTRAINT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SOURCEDATASTATISTICS
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SOURCEFILTER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SOURCEREFERENCE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SOURCESPEC
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SPARKENGINECONFIG
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SPARKSESSIONSTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SPARKSESSIONSTATSUMMAR
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SQLENDPOINT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SQLFEATURESTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SQLINDEX
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SQLINDEXCOLUMN
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_STAGINGINFOATTRIBUTES
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_STATEMEN1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_STATEMENT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_STATOBJECT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_STORAGESEMANTIC
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_STOREDPROCEDURE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_STRATEGY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_STREAMINGCONFIG
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_STRINGDISTANCEENGINE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_STRINGDISTANCEINPUT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_STRINGSETVALUERULE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_STRINGVALUE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_STRUCTURALFEATUREINFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SUBSCRIPTION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_SUBSTITUTEHOLDER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TABLEGROUP
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TABLEPAIR
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TABLEPAIRJOIN
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TAG
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TAGLINKS
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TARGET
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TARGETCONNECTINFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TARGETGROUP
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TARGETHOLDER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TASK
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TASKCONFI1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TASKCONFI2
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TASKCONFIG
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TASKDESCRIPTOR
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TASKINSTANC1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TASKINSTANC2
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TASKINSTANCE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TASKINSTANCEHISTORY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TASKOUTPUTSEEDCONTAIN1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TASKOUTPUTSEEDCONTAINE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TASKRUN
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TASKRUNSTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TASKSCHEDULESTAGESTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TASKSTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TASKUSER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TDGFOREIGNKEY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TDGTABLE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TDGUNIQUEKEY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TESTCASE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TESTCASECOLUMN
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TESTDEFINITIONBADRECOR
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TESTDEFINITIONPARAMETE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TESTDEFINITIONSAMPLING
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TESTDEFINITIONSOURCE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_THRESHOLD
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TIMEOFDAY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TOKSTDOP
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TRANSFORM
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TRANSFORMATIONCONFIGUR
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TRANSFORMATIONFIELDLIS
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TXHANDLERCONFIG
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TXHANDLERCONFIGASSOCIA
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TXHANDLERCONFIGPARTITI
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TYPE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TYPEACONNECTIONATTRIBU
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TYPEBCONNECTIONATTRIBU
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TYPECONFIG
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TYPECONTAINER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TYPEDELEMENT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TYPERCONNECTIONATTRIBU
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TYPERULEENTRY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_TYPESYSTEMMAP
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_UDFREFCOUNTDEPENDENCY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_UMSERVICECONFIG
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_UNIQUEKEY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_USERACCOUNTSECURITYCON
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_USERCREDENTIALS
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_USERDEFINEDFUNCTION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_USERINFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_USERLOCALEINFO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_USERREGULAREXPRESSION
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_UUMNAMESPACE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_VALUE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_VALUEOBJECTMODEL
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_VALUEPATTERN
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_VALUEQUALIFIER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_VALUETOUSERSTUPLE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_VALUETYPE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_VARIABLE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_VARIABLECONTAINE1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_VARIABLECONTAINER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_VARIABLEVALU1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_VARIABLEVALUE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_VERSIONHISTORY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_VERSIONMAPPING
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_VIRTUALFUNCTIONDEFINIT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_VIRTUALPORT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_VIRTUALPROFILEABLERECO
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_VIRTUALSCHEMA
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_VIRTUALTABLE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_VRLDOCUMENT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_VRLELEMENT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_WEIGHTEDDISTANCEENGINE
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_WINDOWKEY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_WINDOWSPEC
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_WORKFLO1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_WORKFLOW
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_WORKFLOWFEATURECONFIG
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_WORKFLOWFEATURESTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_WORKFLOWSTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_WORKFLOWSUMMARYSTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_WORKFLOWUSE1
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_WORKFLOWUSER
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_WSCPUSHINTOMAPENTRY
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_WSDL
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_WSENDPOINT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_WSFEATURESTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_WSOPERATIONSTAT
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_XPATH
WITH FULLSCAN
GO 
UPDATE STATISTICS PO_XSDCONTENT
WITH FULLSCAN
GO 
UPDATE STATISTICS PR_ATTRIBUTE
WITH FULLSCAN
GO 
UPDATE STATISTICS PR_B_RSID_TXID
WITH FULLSCAN
GO 
UPDATE STATISTICS PR_GANNOTATIONS
WITH FULLSCAN
GO 
UPDATE STATISTICS PR_RESOURCE
WITH FULLSCAN
GO 
UPDATE STATISTICS PR_RSID_TXID
WITH FULLSCAN
GO 
